apiVersion: apps/v1beta1 
kind: Deployment
metadata:
  name: grpc-microservice-1
spec:
  selector:
    matchLabels:
      app: grpc-microservice-1
  replicas: 1 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 0%
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: grpc-microservice-1
    spec:
      containers:
        - name: grpc-microservice-1
          image: mornindew/base-demo-protobuf:latest
          command:
            - "./server"
          imagePullPolicy: Always                                                     
          ports:
          - name: http-api
            containerPort: 8888
          resources:
            limits:
              memory: "500Mi"
              cpu: "100m"  
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-microservice-1
spec:
  type: NodePort
  selector:
    app: grpc-microservice-1
  ports:
  - port: 50051
    name: grpc-port                  