version: '2'
services:
  app:
    image: mornindew/grpc-demo-healthcheck-sidecar
    working_dir: /app
    build:
     context: .
     dockerfile: minimal.Dockerfile
    ports:
     - "8080:8080"
    entrypoint:
     - "./server"
    network_mode: host 