// Code generated by protoc-gen-go. DO NOT EDIT.
// source: demo.proto

package genproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ReverseArrayRequest struct {
	ArrayOfNumbers       []float32 `protobuf:"fixed32,1,rep,packed,name=arrayOfNumbers,proto3" json:"arrayOfNumbers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReverseArrayRequest) Reset()         { *m = ReverseArrayRequest{} }
func (m *ReverseArrayRequest) String() string { return proto.CompactTextString(m) }
func (*ReverseArrayRequest) ProtoMessage()    {}
func (*ReverseArrayRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_f5cbe8345c36ee26, []int{0}
}
func (m *ReverseArrayRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReverseArrayRequest.Unmarshal(m, b)
}
func (m *ReverseArrayRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReverseArrayRequest.Marshal(b, m, deterministic)
}
func (dst *ReverseArrayRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReverseArrayRequest.Merge(dst, src)
}
func (m *ReverseArrayRequest) XXX_Size() int {
	return xxx_messageInfo_ReverseArrayRequest.Size(m)
}
func (m *ReverseArrayRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReverseArrayRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReverseArrayRequest proto.InternalMessageInfo

func (m *ReverseArrayRequest) GetArrayOfNumbers() []float32 {
	if m != nil {
		return m.ArrayOfNumbers
	}
	return nil
}

type ReverseArrayResponse struct {
	ReversedArrayOfNumbers []float32 `protobuf:"fixed32,1,rep,packed,name=reversedArrayOfNumbers,proto3" json:"reversedArrayOfNumbers,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}  `json:"-"`
	XXX_unrecognized       []byte    `json:"-"`
	XXX_sizecache          int32     `json:"-"`
}

func (m *ReverseArrayResponse) Reset()         { *m = ReverseArrayResponse{} }
func (m *ReverseArrayResponse) String() string { return proto.CompactTextString(m) }
func (*ReverseArrayResponse) ProtoMessage()    {}
func (*ReverseArrayResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_demo_f5cbe8345c36ee26, []int{1}
}
func (m *ReverseArrayResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReverseArrayResponse.Unmarshal(m, b)
}
func (m *ReverseArrayResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReverseArrayResponse.Marshal(b, m, deterministic)
}
func (dst *ReverseArrayResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReverseArrayResponse.Merge(dst, src)
}
func (m *ReverseArrayResponse) XXX_Size() int {
	return xxx_messageInfo_ReverseArrayResponse.Size(m)
}
func (m *ReverseArrayResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReverseArrayResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReverseArrayResponse proto.InternalMessageInfo

func (m *ReverseArrayResponse) GetReversedArrayOfNumbers() []float32 {
	if m != nil {
		return m.ReversedArrayOfNumbers
	}
	return nil
}

func init() {
	proto.RegisterType((*ReverseArrayRequest)(nil), "ReverseArrayRequest")
	proto.RegisterType((*ReverseArrayResponse)(nil), "ReverseArrayResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ExampleReddiyoGRPCServiceClient is the client API for ExampleReddiyoGRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ExampleReddiyoGRPCServiceClient interface {
	ReverseArray(ctx context.Context, in *ReverseArrayRequest, opts ...grpc.CallOption) (*ReverseArrayResponse, error)
}

type exampleReddiyoGRPCServiceClient struct {
	cc *grpc.ClientConn
}

func NewExampleReddiyoGRPCServiceClient(cc *grpc.ClientConn) ExampleReddiyoGRPCServiceClient {
	return &exampleReddiyoGRPCServiceClient{cc}
}

func (c *exampleReddiyoGRPCServiceClient) ReverseArray(ctx context.Context, in *ReverseArrayRequest, opts ...grpc.CallOption) (*ReverseArrayResponse, error) {
	out := new(ReverseArrayResponse)
	err := c.cc.Invoke(ctx, "/ExampleReddiyoGRPCService/ReverseArray", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleReddiyoGRPCServiceServer is the server API for ExampleReddiyoGRPCService service.
type ExampleReddiyoGRPCServiceServer interface {
	ReverseArray(context.Context, *ReverseArrayRequest) (*ReverseArrayResponse, error)
}

func RegisterExampleReddiyoGRPCServiceServer(s *grpc.Server, srv ExampleReddiyoGRPCServiceServer) {
	s.RegisterService(&_ExampleReddiyoGRPCService_serviceDesc, srv)
}

func _ExampleReddiyoGRPCService_ReverseArray_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReverseArrayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleReddiyoGRPCServiceServer).ReverseArray(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ExampleReddiyoGRPCService/ReverseArray",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleReddiyoGRPCServiceServer).ReverseArray(ctx, req.(*ReverseArrayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ExampleReddiyoGRPCService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ExampleReddiyoGRPCService",
	HandlerType: (*ExampleReddiyoGRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReverseArray",
			Handler:    _ExampleReddiyoGRPCService_ReverseArray_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "demo.proto",
}

func init() { proto.RegisterFile("demo.proto", fileDescriptor_demo_f5cbe8345c36ee26) }

var fileDescriptor_demo_f5cbe8345c36ee26 = []byte{
	// 169 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x49, 0xcd, 0xcd,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xb2, 0xe5, 0x12, 0x0e, 0x4a, 0x2d, 0x4b, 0x2d, 0x2a,
	0x4e, 0x75, 0x2c, 0x2a, 0x4a, 0xac, 0x0c, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x52, 0xe3,
	0xe2, 0x4b, 0x04, 0xf1, 0xfd, 0xd3, 0xfc, 0x4a, 0x73, 0x93, 0x52, 0x8b, 0x8a, 0x25, 0x18, 0x15,
	0x98, 0x35, 0x98, 0x82, 0xd0, 0x44, 0x95, 0xfc, 0xb8, 0x44, 0x50, 0xb5, 0x17, 0x17, 0xe4, 0xe7,
	0x15, 0xa7, 0x0a, 0x99, 0x71, 0x89, 0x15, 0x41, 0xc4, 0x53, 0x1c, 0xb1, 0x99, 0x83, 0x43, 0xd6,
	0x28, 0x82, 0x4b, 0xd2, 0xb5, 0x22, 0x31, 0xb7, 0x20, 0x27, 0x35, 0x28, 0x35, 0x25, 0x25, 0xb3,
	0x32, 0xdf, 0x3d, 0x28, 0xc0, 0x39, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x9a, 0x8b,
	0x07, 0xd9, 0x32, 0x21, 0x11, 0x3d, 0x2c, 0x4e, 0x97, 0x12, 0xd5, 0xc3, 0xe6, 0x22, 0x27, 0xae,
	0x28, 0x8e, 0xf4, 0xd4, 0x3c, 0xb0, 0xa7, 0x93, 0xd8, 0xc0, 0x94, 0x31, 0x20, 0x00, 0x00, 0xff,
	0xff, 0x97, 0xe7, 0x0f, 0xf4, 0x09, 0x01, 0x00, 0x00,
}
