apiVersion: apps/v1beta1 
kind: Deployment
metadata:
  name: orchestrator
spec:
  selector:
    matchLabels:
      app: orchestrator
  replicas: 1 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 4
      maxUnavailable: 0%
  minReadySeconds: 15
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      containers:
        - name: orchestrator
          image: mornindew/reddiyo-os-orchestrator-example:latest
          command:
            - "./server"
          imagePullPolicy: Always 
          readinessProbe:
          httpGet:
              path: /healthz
              port: 8888
          initialDelaySeconds: 5
          periodSeconds: 5                                                     
          ports:
          - name: http-api
            containerPort: 8888
          resources:
            limits:
              memory: "500Mi"
              cpu: "100m"  
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-service
spec:
  type: NodePort
  selector:
    app: orchestrator
  ports:
  - port: 80
    name: http-auth                  
    targetPort: 8888